version: '3.8'

services:
  # Backend FastAPI
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://orbit:orbit@postgres:5432/orbit
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    volumes:
      - ./apps/backend:/app
    networks:
      - orbit-network

  # Frontend React/Vite
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:5173"
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    networks:
      - orbit-network
    depends_on:
      - backend

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=orbit
      - POSTGRES_USER=orbit
      - POSTGRES_PASSWORD=orbit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - orbit-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - orbit-network

volumes:
  postgres_data:
  redis_data:

networks:
  orbit-network:
    driver: bridge

