"""add_webhook_fields_to_documents

Revision ID: 9baf8d5198ff
Revises: e67862bf5469
Create Date: 2025-07-04 20:49:54.334678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9baf8d5198ff'
down_revision: Union[str, None] = 'e67862bf5469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('webhook_received', sa.Boolean(), nullable=True))
    op.add_column('documents', sa.Column('webhook_received_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'webhook_received_at')
    op.drop_column('documents', 'webhook_received')
    # ### end Alembic commands ###
