"""add_wu3_fields_to_documents

Revision ID: e67862bf5469
Revises: 41c5f2d84848
Create Date: 2025-07-04 20:26:52.991108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e67862bf5469'
down_revision: Union[str, None] = '41c5f2d84848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('wu3_document_id', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('wu3_request_id', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('error_message', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('processing_time_seconds', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('wu3_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'wu3_version')
    op.drop_column('documents', 'processing_time_seconds')
    op.drop_column('documents', 'error_message')
    op.drop_column('documents', 'wu3_request_id')
    op.drop_column('documents', 'wu3_document_id')
    # ### end Alembic commands ###
