"""add_gpt_insights_fields_to_documents

Revision ID: f6a8aa2b3cc6
Revises: 9baf8d5198ff
Create Date: 2025-07-04 21:01:29.374108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6a8aa2b3cc6'
down_revision: Union[str, None] = '9baf8d5198ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('gpt_insights', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('gpt_summary', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('gpt_generated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('gpt_model_used', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('insights_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'insights_status')
    op.drop_column('documents', 'gpt_model_used')
    op.drop_column('documents', 'gpt_generated_at')
    op.drop_column('documents', 'gpt_summary')
    op.drop_column('documents', 'gpt_insights')
    # ### end Alembic commands ###
